# Generated by Django 5.2.8 on 2025-11-09 07:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brand_remove_product_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_defect',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_ok',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
