# Generated by Django 5.1.2 on 2025-11-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dealer',
        ),
    ]
