# Generated by Django 5.1.2 on 2025-12-05 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_style_product_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DoorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, help_text='Цветовой код или артикул', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Door Color',
                'verbose_name_plural': 'Door Colors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.collection')),
            ],
            options={
                'verbose_name': 'Door Model',
                'verbose_name_plural': 'Door Models',
                'ordering': ('collection', 'name'),
                'unique_together': {('collection', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='catalog.product')),
                ('door_type', models.CharField(blank=True, choices=[('ПГ', 'ПГ (Полотно глухое)'), ('ПО', 'ПО (Полотно остеклённое)'), ('ПДО', 'ПДО (Полотно частично остеклённое)'), ('ПДГ', 'ПДГ (Полотно с декоративными элементами)')], max_length=10)),
                ('door_size', models.CharField(blank=True, choices=[('400мм', '400мм'), ('600мм', '600мм'), ('700мм', '700мм'), ('800мм', '800мм'), ('900мм', '900мм'), ('20-6', '20-6'), ('20-7', '20-7'), ('20-8', '20-8'), ('20-9', '20-9'), ('21-6', '21-6'), ('21-7', '21-7'), ('21-8', '21-8'), ('21-9', '21-9'), ('other', 'Другой размер')], max_length=20)),
                ('custom_size', models.CharField(blank=True, help_text='Если размер не из списка', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_metas', to='catalog.collection')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_metas', to='catalog.doorcolor')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_metas', to='catalog.doormodel')),
            ],
            options={
                'verbose_name': 'Product Metadata',
                'verbose_name_plural': 'Product Metadata',
            },
        ),
    ]
