# Generated by Django 5.1.2 on 2025-12-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_add_sku_and_configurations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doormodel',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='color',
        ),
        migrations.AlterUniqueTogether(
            name='doormodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='model',
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='doorkitcomponent',
            options={'ordering': ('variant', 'component'), 'verbose_name': 'Комплектующий элемент двери', 'verbose_name_plural': 'Комплектующие элементы двери'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('brand__name', 'collection', 'model_name'), 'verbose_name': 'Product Model', 'verbose_name_plural': 'Product Models'},
        ),
        migrations.AlterModelOptions(
            name='productsku',
            options={'ordering': ('variant', 'size'), 'verbose_name': 'Product SKU', 'verbose_name_plural': 'Product SKUs'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('product_model', 'color', 'door_type'), 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterField(
            model_name='doorkitcomponent',
            name='component',
            field=models.ForeignKey(help_text='Погонаж: наличник, коробка, добор и т.д.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='product',
            field=models.OneToOneField(help_text="Существующий продукт из ERP (orderlar, to'lovlar va boshqa ma'lumotlar bu yerda)", on_delete=django.db.models.deletion.CASCADE, related_name='catalog_sku', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='size',
            field=models.CharField(choices=[('400мм', '400мм'), ('600мм', '600мм'), ('700мм', '700мм'), ('800мм', '800мм'), ('900мм', '900мм'), ('20-6', '20-6'), ('20-7', '20-7'), ('20-8', '20-8'), ('20-9', '20-9'), ('21-6', '21-6'), ('21-7', '21-7'), ('21-8', '21-8'), ('21-9', '21-9'), ('other', 'Другой размер')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(help_text='Цвет/ранг (белый, кремовый, тач-серый, дуб грей)', max_length=150),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='door_type',
            field=models.CharField(choices=[('ПГ', 'ПГ (Полотно глухое)'), ('ПО', 'ПО (Полотно остеклённое)'), ('ПДО', 'ПДО (Полотно частично остеклённое)'), ('ПДГ', 'ПДГ (Полотно с декоративными элементами)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение варианта', null=True, upload_to='catalog/variants/'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='DoorColor',
        ),
        migrations.DeleteModel(
            name='DoorModel',
        ),
        migrations.DeleteModel(
            name='ProductMeta',
        ),
    ]
