# Generated by Django 5.1.2 on 2025-12-08 13:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_productvariant_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmeta",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="doormodel",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="productmeta",
            name="color",
        ),
        migrations.AlterUniqueTogether(
            name="doormodel",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productmeta",
            name="model",
        ),
        migrations.RemoveField(
            model_name="productmeta",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ("name",),
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="doorkitcomponent",
            options={
                "ordering": ("variant", "component"),
                "verbose_name": "Комплектующий элемент двери",
                "verbose_name_plural": "Комплектующие элементы двери",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productmodel",
            options={
                "ordering": ("brand__name", "collection", "model_name"),
                "verbose_name": "Product Model",
                "verbose_name_plural": "Product Models",
            },
        ),
        migrations.AlterModelOptions(
            name="productsku",
            options={
                "ordering": ("variant", "size"),
                "verbose_name": "Product SKU",
                "verbose_name_plural": "Product SKUs",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ("product_model", "color", "door_type"),
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
            },
        ),
        migrations.AlterModelOptions(
            name="style",
            options={
                "ordering": ("name",),
                "verbose_name": "Style",
                "verbose_name_plural": "Styles",
            },
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                help_text="Unique name of the brand",
                max_length=120,
                unique=True,
                verbose_name="Brand name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the category",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Unique name of the product category",
                max_length=120,
                unique=True,
                verbose_name="Category name",
            ),
        ),
        migrations.AlterField(
            model_name="doorkitcomponent",
            name="component",
            field=models.ForeignKey(
                help_text="Погонаж: наличник, коробка, добор и т.д.",
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.product",
                verbose_name="Компонент",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique barcode",
                max_length=32,
                unique=True,
                verbose_name="Barcode",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                help_text="Brand of the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Product category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Purchase cost in USD",
                max_digits=12,
                verbose_name="Cost (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when product was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product photo or image",
                null=True,
                upload_to="products/",
                verbose_name="Product image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this product is active in the system",
                verbose_name="Active status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Full name of the product",
                max_length=255,
                verbose_name="Product name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sell_price_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Selling price in USD",
                max_digits=12,
                verbose_name="Selling price (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="Product size or dimensions",
                max_length=64,
                verbose_name="Size",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                help_text="Stock Keeping Unit - unique product identifier",
                max_length=64,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_defect",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Quantity of defective stock",
                max_digits=14,
                verbose_name="Stock (Defect)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_ok",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Quantity of good stock available",
                max_digits=14,
                verbose_name="Stock (OK)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="style",
            field=models.ForeignKey(
                blank=True,
                help_text="Product style (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.style",
                verbose_name="Style",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                default="pcs",
                help_text="Unit of measure (pcs, kg, m, etc.)",
                max_length=32,
                verbose_name="Unit of measure",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last update",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="product",
            field=models.OneToOneField(
                help_text="Существующий продукт из ERP (orderlar, to'lovlar va boshqa ma'lumotlar bu yerda)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_sku",
                to="catalog.product",
            ),
        ),
        migrations.AlterField(
            model_name="productsku",
            name="size",
            field=models.CharField(
                choices=[
                    ("400мм", "400мм"),
                    ("600мм", "600мм"),
                    ("700мм", "700мм"),
                    ("800мм", "800мм"),
                    ("900мм", "900мм"),
                    ("20-6", "20-6"),
                    ("20-7", "20-7"),
                    ("20-8", "20-8"),
                    ("20-9", "20-9"),
                    ("21-6", "21-6"),
                    ("21-7", "21-7"),
                    ("21-8", "21-8"),
                    ("21-9", "21-9"),
                    ("other", "Другой размер"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.CharField(
                help_text="Цвет/ранг (белый, кремовый, тач-серый, дуб грей)",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="door_type",
            field=models.CharField(
                choices=[
                    ("ПГ", "ПГ (Полотно глухое)"),
                    ("ПО", "ПО (Полотно остеклённое)"),
                    ("ПДО", "ПДО (Полотно частично остеклённое)"),
                    ("ПДГ", "ПДГ (Полотно с декоративными элементами)"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Основное изображение варианта",
                null=True,
                upload_to="catalog/variants/",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of the style",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this style is currently active",
                verbose_name="Active status",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="name",
            field=models.CharField(
                help_text="Unique name of the product style",
                max_length=150,
                unique=True,
                verbose_name="Style name",
            ),
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.DeleteModel(
            name="DoorColor",
        ),
        migrations.DeleteModel(
            name="DoorModel",
        ),
        migrations.DeleteModel(
            name="ProductMeta",
        ),
    ]
