# Generated by Django 5.1.2 on 2025-12-12 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def safe_remove_old_models(apps, schema_editor):
    """
    Safely remove old models if they exist.
    These models may have been already removed in previous migrations.
    """
    with schema_editor.connection.cursor() as cursor:
        # Check and drop ProductMeta table if exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'catalog_productmeta'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute("DROP TABLE catalog_productmeta CASCADE;")

        # Check and drop DoorModel table if exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'catalog_doormodel'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute("DROP TABLE catalog_doormodel CASCADE;")

        # Check and drop DoorColor table if exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'catalog_doorcolor'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute("DROP TABLE catalog_doorcolor CASCADE;")

        # Check and drop Collection table if exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = 'catalog_collection'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute("DROP TABLE catalog_collection CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_productmeta_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип дефекта (например: дошечка, стекло, стойка)', max_length=200, unique=True, verbose_name='Название типа дефекта')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание типа дефекта', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли этот тип дефекта', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип дефекта',
                'verbose_name_plural': 'Типы дефектов',
                'ordering': ('name',),
            },
        ),
        # Safely remove old models using custom SQL
        migrations.RunPython(safe_remove_old_models, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ProductDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общее количество дефектных единиц', max_digits=14, verbose_name='Общее количество дефектов')),
                ('repairable_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Количество единиц, которые можно отремонтировать', max_digits=14, verbose_name='Количество ремонтопригодных')),
                ('non_repairable_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Количество единиц, которые нельзя отремонтировать', max_digits=14, verbose_name='Количество неремонтопригодных')),
                ('defect_details', models.JSONField(blank=True, default=list, help_text='JSON массив: [{"type_id": 1, "type_name": "дошечка", "qty": 2}]', verbose_name='Детали дефектов')),
                ('status', models.CharField(choices=[('detected', 'Обнаружен'), ('inspected', 'Проверен'), ('repairing', 'В ремонте'), ('repaired', 'Отремонтирован'), ('disposed', 'Утилизирован'), ('sold_outlet', 'Продан outlet')], default='detected', help_text='Текущий статус дефекта', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание дефекта', verbose_name='Описание')),
                ('repair_materials', models.JSONField(blank=True, default=list, help_text='JSON массив: [{"product_id": 123, "product_name": "...", "qty": 2}]', verbose_name='Материалы для ремонта')),
                ('repair_completed_at', models.DateTimeField(blank=True, help_text='Когда был завершен ремонт', null=True, verbose_name='Дата завершения ремонта')),
                ('disposed_at', models.DateTimeField(blank=True, help_text='Когда был утилизирован', null=True, verbose_name='Дата утилизации')),
                ('sold_outlet_at', models.DateTimeField(blank=True, help_text='Когда был продан через outlet', null=True, verbose_name='Дата продажи outlet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший запись о дефекте', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_defects', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('product', models.ForeignKey(help_text='Продукт с дефектом', on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='catalog.product', verbose_name='Продукт')),
                ('updated_by', models.ForeignKey(help_text='Пользователь, последним обновивший запись', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_defects', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Дефект продукта',
                'verbose_name_plural': 'Дефекты продуктов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DefectAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('status_changed', 'Статус изменен'), ('repaired', 'Отремонтирован'), ('disposed', 'Утилизирован'), ('sold_outlet', 'Продан outlet')], max_length=20, verbose_name='Действие')),
                ('old_data', models.JSONField(blank=True, help_text='Снимок данных до изменения', null=True, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, help_text='Снимок данных после изменения', null=True, verbose_name='Новые данные')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание действия', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='catalog.productdefect', verbose_name='Дефект')),
            ],
            options={
                'verbose_name': 'Лог изменений дефекта',
                'verbose_name_plural': 'Логи изменений дефектов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='productdefect',
            index=models.Index(fields=['product', 'status'], name='catalog_pro_product_a781f8_idx'),
        ),
        migrations.AddIndex(
            model_name='productdefect',
            index=models.Index(fields=['status', '-created_at'], name='catalog_pro_status_2dfeec_idx'),
        ),
        migrations.AddIndex(
            model_name='productdefect',
            index=models.Index(fields=['created_at'], name='catalog_pro_created_95265c_idx'),
        ),
        migrations.AddIndex(
            model_name='defectauditlog',
            index=models.Index(fields=['defect', '-created_at'], name='catalog_def_defect__2c4409_idx'),
        ),
        migrations.AddIndex(
            model_name='defectauditlog',
            index=models.Index(fields=['-created_at'], name='catalog_def_created_9c73ab_idx'),
        ),
    ]
