# Generated by Django 5.1.2 on 2025-12-20 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_inbound_inbounditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price amount', max_digits=12, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', help_text='Currency of the price', max_length=3, verbose_name='Currency')),
                ('valid_from', models.DateField(help_text='Date from which this price is effective', verbose_name='Valid from')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this price record was created', verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ('-valid_from',),
            },
        ),
        migrations.RemoveField(
            model_name='doormodel',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='color',
        ),
        migrations.AlterUniqueTogether(
            name='doormodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='model',
        ),
        migrations.RemoveField(
            model_name='productmeta',
            name='product',
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_created_3d740e_idx',
            old_name='catalog_inb_created_idx',
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_date_bec190_idx',
            old_name='catalog_inb_date_idx',
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_status_b14d65_idx',
            old_name='catalog_inb_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_brand_i_000841_idx',
            old_name='catalog_inb_brand_d_idx',
        ),
        migrations.RenameIndex(
            model_name='inbounditem',
            new_name='catalog_inb_inbound_6b63bb_idx',
            old_name='catalog_inb_inbound_idx',
        ),
        migrations.RenameIndex(
            model_name='inbounditem',
            new_name='catalog_inb_product_a36c2a_idx',
            old_name='catalog_inb_product_idx',
        ),
        migrations.AddField(
            model_name='productprice',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this price record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(help_text='Product this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='Product'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='DoorColor',
        ),
        migrations.DeleteModel(
            name='DoorModel',
        ),
        migrations.DeleteModel(
            name='ProductMeta',
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', '-valid_from'], name='catalog_pro_product_42d34f_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['valid_from'], name='catalog_pro_valid_f_7a847f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'valid_from')},
        ),
    ]
