# Generated by Django 5.1.2 on 2025-12-20 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_table_exists(schema_editor, table_name):
    """Check if a table exists in the database."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [table_name])
        return cursor.fetchone()[0]


def safe_remove_field(apps, schema_editor, model_name, field_name):
    """Safely remove a field only if the table exists."""
    table_name = f"catalog_{model_name.lower()}"
    if check_table_exists(schema_editor, table_name):
        try:
            model = apps.get_model('catalog', model_name)
            field = model._meta.get_field(field_name)
            schema_editor.remove_field(model, field)
        except Exception as e:
            print(f"Warning: Could not remove {model_name}.{field_name}: {e}")


def safe_delete_model(apps, schema_editor, model_name):
    """Safely delete a model only if the table exists."""
    table_name = f"catalog_{model_name.lower()}"
    if check_table_exists(schema_editor, table_name):
        try:
            model = apps.get_model('catalog', model_name)
            schema_editor.delete_model(model)
        except Exception as e:
            print(f"Warning: Could not delete model {model_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_inbound_inbounditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price amount', max_digits=12, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', help_text='Currency of the price', max_length=3, verbose_name='Currency')),
                ('valid_from', models.DateField(help_text='Date from which this price is effective', verbose_name='Valid from')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this price record was created', verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ('-valid_from',),
            },
        ),
        # Safe removal of fields - only if tables exist
        migrations.RunPython(
            lambda apps, schema_editor: safe_remove_field(apps, schema_editor, 'DoorModel', 'collection'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: safe_remove_field(apps, schema_editor, 'ProductMeta', 'collection'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: safe_remove_field(apps, schema_editor, 'ProductMeta', 'color'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: safe_remove_field(apps, schema_editor, 'ProductMeta', 'model'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: safe_remove_field(apps, schema_editor, 'ProductMeta', 'product'),
            migrations.RunPython.noop,
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_created_3d740e_idx',
            old_name='catalog_inb_created_idx',
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_date_bec190_idx',
            old_name='catalog_inb_date_idx',
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_status_b14d65_idx',
            old_name='catalog_inb_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inbound',
            new_name='catalog_inb_brand_i_000841_idx',
            old_name='catalog_inb_brand_d_idx',
        ),
        migrations.RenameIndex(
            model_name='inbounditem',
            new_name='catalog_inb_inbound_6b63bb_idx',
            old_name='catalog_inb_inbound_idx',
        ),
        migrations.RenameIndex(
            model_name='inbounditem',
            new_name='catalog_inb_product_a36c2a_idx',
            old_name='catalog_inb_product_idx',
        ),
        migrations.AddField(
            model_name='productprice',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this price record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(help_text='Product this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='Product'),
        ),
        # Safe deletion of models - only if tables exist
        migrations.RunPython(
            lambda apps, schema_editor: safe_delete_model(apps, schema_editor, 'Collection'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: safe_delete_model(apps, schema_editor, 'DoorColor'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: safe_delete_model(apps, schema_editor, 'DoorModel'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, schema_editor: safe_delete_model(apps, schema_editor, 'ProductMeta'),
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', '-valid_from'], name='catalog_pro_product_42d34f_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['valid_from'], name='catalog_pro_valid_f_7a847f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'valid_from')},
        ),
    ]
