# Generated by Django 5.1.2 on 2025-12-14 18:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_defects_v2_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # These operations update Django's state only, as the tables were already
        # dropped in migration 0014. Using SeparateDatabaseAndState prevents
        # attempting to modify non-existent tables.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='productmeta',
                    name='collection',
                ),
                migrations.RemoveField(
                    model_name='doormodel',
                    name='collection',
                ),
                migrations.RemoveField(
                    model_name='productmeta',
                    name='color',
                ),
                migrations.AlterUniqueTogether(
                    name='doormodel',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='productmeta',
                    name='model',
                ),
                migrations.RemoveField(
                    model_name='productmeta',
                    name='product',
                ),
            ],
            # No database operations needed - tables already dropped in 0014
            database_operations=[],
        ),
        migrations.AlterModelOptions(
            name='defectauditlogv2',
            options={'ordering': ['-performed_at'], 'verbose_name': 'Лог аудита брака', 'verbose_name_plural': 'Логи аудита брака'},
        ),
        migrations.AlterModelOptions(
            name='defectbatchv2',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Партия брака', 'verbose_name_plural': 'Партии брака'},
        ),
        migrations.AlterModelOptions(
            name='defectdetailv2',
            options={'ordering': ['-qty'], 'verbose_name': 'Детализация дефекта', 'verbose_name_plural': 'Детализация дефектов'},
        ),
        migrations.AlterModelOptions(
            name='defectrepairv2',
            options={'ordering': ['-started_at'], 'verbose_name': 'Ремонт брака', 'verbose_name_plural': 'Ремонты брака'},
        ),
        migrations.AlterModelOptions(
            name='defectwriteoffv2',
            options={'ordering': ['-performed_at'], 'verbose_name': 'Списание брака', 'verbose_name_plural': 'Списания брака'},
        ),
        migrations.AlterModelOptions(
            name='repairmaterialv2',
            options={'ordering': ['-qty_used'], 'verbose_name': 'Материал ремонта', 'verbose_name_plural': 'Материалы ремонта'},
        ),
        migrations.AlterModelOptions(
            name='sparepartv2',
            options={'ordering': ['name'], 'verbose_name': 'Запасная часть', 'verbose_name_plural': 'Запасные части'},
        ),
        migrations.RemoveIndex(
            model_name='defectauditlogv2',
            name='idx_audit_v2_batch_performed',
        ),
        migrations.RemoveIndex(
            model_name='defectbatchv2',
            name='idx_defect_batch_v2_detected',
        ),
        migrations.RenameIndex(
            model_name='defectbatchv2',
            new_name='defect_batc_product_0ef083_idx',
            old_name='idx_defect_batch_v2_prod_stat',
        ),
        migrations.RenameIndex(
            model_name='defectrepairv2',
            new_name='defect_repa_batch_i_200380_idx',
            old_name='idx_repair_v2_batch_status',
        ),
        migrations.RenameIndex(
            model_name='defectwriteoffv2',
            new_name='defect_writ_batch_i_619249_idx',
            old_name='idx_writeoff_v2_batch_reason',
        ),
        migrations.AlterField(
            model_name='defectauditlogv2',
            name='action',
            field=models.CharField(choices=[('created', 'Создан'), ('inspected', 'Проверен'), ('repair_started', 'Ремонт начат'), ('repair_completed', 'Ремонт завершен'), ('written_off', 'Списан'), ('status_changed', 'Статус изменен'), ('quantity_adjusted', 'Количество скорректировано')], max_length=30, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='defectauditlogv2',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='catalog.defectbatchv2', verbose_name='Партия брака'),
        ),
        migrations.AlterField(
            model_name='defectauditlogv2',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='defectauditlogv2',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Новые данные'),
        ),
        migrations.AlterField(
            model_name='defectauditlogv2',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Старые данные'),
        ),
        migrations.AlterField(
            model_name='defectauditlogv2',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='defectauditlogv2',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_defect_batches', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='non_repairable_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Количество, которое нельзя отремонтировать', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Неремонтопригодных'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_batches', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='repairable_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Количество, которое можно отремонтировать', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ремонтопригодных'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание проверки'), ('inspected', 'Проверен'), ('processing', 'В обработке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, help_text='Всего дефектных единиц', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Общее количество'),
        ),
        migrations.AlterField(
            model_name='defectbatchv2',
            name='warehouse_name',
            field=models.CharField(blank=True, help_text='Название склада где обнаружен дефект', max_length=200, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='defectdetailv2',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_details', to='catalog.defectbatchv2', verbose_name='Партия брака'),
        ),
        migrations.AlterField(
            model_name='defectdetailv2',
            name='defect_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_occurrences', to='catalog.defecttype', verbose_name='Тип дефекта'),
        ),
        migrations.AlterField(
            model_name='defectdetailv2',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='defectdetailv2',
            name='qty',
            field=models.DecimalField(decimal_places=2, help_text='Количество единиц с этим дефектом', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='defectrepairv2',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repairs', to='catalog.defectbatchv2', verbose_name='Партия брака'),
        ),
        migrations.AlterField(
            model_name='defectrepairv2',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершение ремонта'),
        ),
        migrations.AlterField(
            model_name='defectrepairv2',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='defectrepairv2',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_repairs', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил'),
        ),
        migrations.AlterField(
            model_name='defectrepairv2',
            name='qty_repaired',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество отремонтированных'),
        ),
        migrations.AlterField(
            model_name='defectrepairv2',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало ремонта'),
        ),
        migrations.AlterField(
            model_name='defectrepairv2',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('failed', 'Не удался')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='defectwriteoffv2',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='catalog.defectbatchv2', verbose_name='Партия брака'),
        ),
        migrations.AlterField(
            model_name='defectwriteoffv2',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='defectwriteoffv2',
            name='performed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата списания'),
        ),
        migrations.AlterField(
            model_name='defectwriteoffv2',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_write_offs', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил'),
        ),
        migrations.AlterField(
            model_name='defectwriteoffv2',
            name='qty_written_off',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество списанных'),
        ),
        migrations.AlterField(
            model_name='defectwriteoffv2',
            name='reason',
            field=models.CharField(choices=[('disposal', 'Утилизация'), ('scrap', 'Списание'), ('outlet_sale', 'Продажа через outlet'), ('other', 'Прочее')], default='disposal', max_length=20, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='defectwriteoffv2',
            name='sale_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена продажи (USD)'),
        ),
        migrations.AlterField(
            model_name='repairmaterialv2',
            name='qty_used',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Использовано'),
        ),
        migrations.AlterField(
            model_name='repairmaterialv2',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.defectrepairv2', verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='repairmaterialv2',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_history', to='catalog.sparepartv2', verbose_name='Запасная часть'),
        ),
        migrations.AlterField(
            model_name='repairmaterialv2',
            name='total_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Общая стоимость (USD)'),
        ),
        migrations.AlterField(
            model_name='repairmaterialv2',
            name='unit_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Захватывается на момент использования', max_digits=14, null=True, verbose_name='Цена за единицу (USD)'),
        ),
        migrations.AlterField(
            model_name='sparepartv2',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='sparepartv2',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Уровень для предупреждения о низком запасе', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='sparepartv2',
            name='name',
            field=models.CharField(help_text="Удобное название (например: 'yon stoyevoy')", max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sparepartv2',
            name='product',
            field=models.OneToOneField(help_text='Ссылка на продукт в каталоге', on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_info', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='sparepartv2',
            name='unit',
            field=models.CharField(default='dona', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterUniqueTogether(
            name='repairmaterialv2',
            unique_together={('repair', 'spare_part')},
        ),
        migrations.AddIndex(
            model_name='defectauditlogv2',
            index=models.Index(fields=['batch', '-performed_at'], name='defect_audi_batch_i_9b612b_idx'),
        ),
        migrations.AddIndex(
            model_name='defectauditlogv2',
            index=models.Index(fields=['performed_by', '-performed_at'], name='defect_audi_perform_3fda2e_idx'),
        ),
        migrations.AddIndex(
            model_name='defectbatchv2',
            index=models.Index(fields=['status', '-detected_at'], name='defect_batc_status_cbb80e_idx'),
        ),
        migrations.AddIndex(
            model_name='defectbatchv2',
            index=models.Index(fields=['-detected_at'], name='defect_batc_detecte_05154c_idx'),
        ),
        migrations.AddIndex(
            model_name='defectrepairv2',
            index=models.Index(fields=['-started_at'], name='defect_repa_started_278120_idx'),
        ),
        migrations.AddIndex(
            model_name='defectwriteoffv2',
            index=models.Index(fields=['-performed_at'], name='defect_writ_perform_3c1332_idx'),
        ),
        migrations.AlterModelTable(
            name='defectauditlogv2',
            table='defect_audit_logs',
        ),
        migrations.AlterModelTable(
            name='defectbatchv2',
            table='defect_batches',
        ),
        migrations.AlterModelTable(
            name='defectdetailv2',
            table='defect_details',
        ),
        migrations.AlterModelTable(
            name='defectrepairv2',
            table='defect_repairs',
        ),
        migrations.AlterModelTable(
            name='defectwriteoffv2',
            table='defect_write_offs',
        ),
        migrations.AlterModelTable(
            name='repairmaterialv2',
            table='repair_materials',
        ),
        migrations.AlterModelTable(
            name='sparepartv2',
            table='spare_parts',
        ),
        # Delete old models (state only - tables already dropped in 0014)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Collection',
                ),
                migrations.DeleteModel(
                    name='DoorColor',
                ),
                migrations.DeleteModel(
                    name='DoorModel',
                ),
                migrations.DeleteModel(
                    name='ProductMeta',
                ),
            ],
            # No database operations needed - tables already dropped in 0014
            database_operations=[],
        ),
    ]
