# Generated by Django 5.1.2 on 2025-12-20 16:52

from django.db import migrations
from django.utils import timezone


def migrate_product_prices(apps, schema_editor):
    """
    Migrate existing sell_price_usd from Product to ProductPrice.
    Creates initial price history for all products with sell_price_usd > 0.
    """
    Product = apps.get_model('catalog', 'Product')
    ProductPrice = apps.get_model('catalog', 'ProductPrice')
    
    products = Product.objects.filter(sell_price_usd__gt=0)
    
    price_records = []
    for product in products:
        # Use product creation date as valid_from
        valid_from = product.created_at.date() if product.created_at else timezone.now().date()
        
        price_records.append(
            ProductPrice(
                product=product,
                price=product.sell_price_usd,
                currency='USD',
                valid_from=valid_from,
                created_by=None,  # System migration
            )
        )
    
    # Bulk create all price records
    if price_records:
        ProductPrice.objects.bulk_create(price_records, ignore_conflicts=True)
        print(f"Migrated {len(price_records)} product prices to ProductPrice model.")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - delete all ProductPrice records.
    Note: This is destructive and should only be used in development.
    """
    ProductPrice = apps.get_model('catalog', 'ProductPrice')
    count = ProductPrice.objects.count()
    ProductPrice.objects.all().delete()
    print(f"Deleted {count} ProductPrice records.")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productprice_remove_doormodel_collection_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_product_prices, reverse_migration),
    ]
