# Generated by Django 5.1.2 on 2025-11-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
