# Generated by Django 5.1.2 on 2025-12-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_qty_alter_orderreturn_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
