# Generated by Django 5.1.2 on 2025-12-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate used for this order (1 USD = X UZS)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate_date',
            field=models.DateField(blank=True, help_text='Date when exchange rate was applied', null=True),
        ),
    ]
