# Generated by Django 5.1.2 on 2025-12-05 13:09

from decimal import Decimal
from django.db import migrations, models


def populate_return_exchange_rates(apps, schema_editor):
    """
    Populate exchange_rate and amount_uzs for existing OrderReturns
    using their order's exchange rate
    """
    OrderReturn = apps.get_model('orders', 'OrderReturn')
    
    for return_obj in OrderReturn.objects.select_related('order').all():
        if return_obj.order and return_obj.order.exchange_rate:
            return_obj.exchange_rate = return_obj.order.exchange_rate
            return_obj.exchange_rate_date = return_obj.order.exchange_rate_date
            
            # Calculate amount_uzs using order's rate
            if return_obj.amount_usd and return_obj.exchange_rate:
                return_obj.amount_uzs = (
                    Decimal(str(return_obj.amount_usd)) * 
                    Decimal(str(return_obj.exchange_rate))
                ).quantize(Decimal('0.01'))
            
            return_obj.save(update_fields=['exchange_rate', 'exchange_rate_date', 'amount_uzs'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_exchange_rate_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='amount_uzs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Return amount in UZS (using order exchange rate)', max_digits=18),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate from order (1 USD = X UZS)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='exchange_rate_date',
            field=models.DateField(blank=True, help_text='Exchange rate date from order', null=True),
        ),
        migrations.RunPython(populate_return_exchange_rates, reverse_code=migrations.RunPython.noop),
    ]
