# Generated by Django 5.1.2 on 2025-12-05 13:16

from decimal import Decimal
from django.db import migrations


def populate_order_exchange_rates(apps, schema_editor):
    """Populate exchange_rate, exchange_rate_date and total_uzs for existing orders."""
    Order = apps.get_model('orders', 'Order')
    
    # Import here to avoid circular imports
    from core.utils.currency import get_exchange_rate
    
    orders_to_update = []
    
    for order in Order.objects.filter(exchange_rate__isnull=True):
        # Get exchange rate for order date
        rate, rate_date = get_exchange_rate(order.value_date)
        
        order.exchange_rate = rate
        order.exchange_rate_date = rate_date
        order.total_uzs = (order.total_usd * rate).quantize(Decimal('0.01'))
        
        orders_to_update.append(order)
    
    if orders_to_update:
        Order.objects.bulk_update(
            orders_to_update,
            ['exchange_rate', 'exchange_rate_date', 'total_uzs'],
            batch_size=100
        )
        print(f"Updated {len(orders_to_update)} orders with exchange rates")


def reverse_populate(apps, schema_editor):
    """Reverse migration - set exchange rate fields to null."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.update(exchange_rate=None, exchange_rate_date=None, total_uzs=0)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_exchange_rate_to_orderreturn'),
    ]

    operations = [
        migrations.RunPython(populate_order_exchange_rates, reverse_populate),
    ]
