# Generated by Django 5.1.2 on 2025-12-10 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_productmeta_collection_and_more'),
        ('dealers', '0004_alter_dealer_options_alter_region_options_and_more'),
        ('orders', '0011_add_discount_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when order was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(help_text='Customer/dealer who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dealers.dealer', verbose_name='Dealer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='display_no',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique order display number', max_length=32, unique=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate used for this order (1 USD = X UZS)', max_digits=12, null=True, verbose_name='Exchange rate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_rate_date',
            field=models.DateField(blank=True, help_text='Date when exchange rate was applied', null=True, verbose_name='Exchange rate date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Whether this order was imported from external source', verbose_name='Imported'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_reserve',
            field=models.BooleanField(default=False, help_text='Whether this is a reserve order', verbose_name='Reserve order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes or comments about the order', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='created', help_text='Current status of the order', max_length=20, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total order amount in USD', max_digits=14, verbose_name='Total (USD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_uzs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total order amount in UZS', max_digits=18, verbose_name='Total (UZS)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date for financial accounting', verbose_name='Value date'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit price in USD', max_digits=12, verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='Product ordered', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, help_text='Quantity ordered (must be greater than 0)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='reserved', help_text='Current status of this order item', max_length=20, verbose_name='Item status'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of status change', verbose_name='Changed at'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='by_user',
            field=models.ForeignKey(blank=True, help_text='User who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='new_status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], help_text='New status after change', max_length=20, verbose_name='New status'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='old_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], help_text='Previous status before change', max_length=20, null=True, verbose_name='Old status'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(help_text='Order being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='Order'),
        ),
    ]
