# Generated by Django 5.1.2 on 2025-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency used for this order item', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price at the time of order creation (immutable)', max_digits=12, null=True, verbose_name='Price at time'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit price in USD at the time of order (DEPRECATED - use price_at_time)', max_digits=12, verbose_name='Price (USD)'),
        ),
    ]
