# Generated by Django 5.1.2 on 2025-12-03 18:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0005_add_debt_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank')], max_length=10)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('type', 'currency', 'name'),
                'unique_together': {('type', 'currency', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in original currency', max_digits=18)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount in USD equivalent', max_digits=18)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate UZS to USD (for UZS transactions)', max_digits=12, null=True)),
                ('exchange_rate_date', models.DateField(blank=True, help_text='Date when exchange rate was taken', null=True)),
                ('category', models.CharField(blank=True, help_text='Required for expense transactions', max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financeaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_finance_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_transactions', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(blank=True, help_text='Required for income, null for expense', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transactions', to='dealers.dealer')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['type', 'status'], name='finance_fin_type_574bcc_idx'), models.Index(fields=['dealer', 'status'], name='finance_fin_dealer__a3818e_idx'), models.Index(fields=['date'], name='finance_fin_date_4c2559_idx'), models.Index(fields=['account'], name='finance_fin_account_028643_idx')],
            },
        ),
    ]
