# Generated by Django 5.1.2 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_cash_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Amount in USD equivalent (auto-calculated)', max_digits=18, null=True),
        ),
    ]
