# Generated by Django 5.1.2 on 2025-12-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_exchangerate"),
        ("finance", "0003_alter_financetransaction_amount_usd"),
    ]

    operations = []
