# Generated by Django 5.1.2 on 2025-12-05 14:12

from decimal import Decimal
from django.db import migrations, models


def populate_amount_uzs(apps, schema_editor):
    """
    Populate amount_uzs and exchange_rate for existing transactions.
    Each transaction stores its own exchange rate from transaction date.
    """
    FinanceTransaction = apps.get_model('finance', 'FinanceTransaction')
    
    # Import here to avoid circular imports
    from core.utils.currency import get_exchange_rate
    
    transactions_to_update = []
    
    for transaction in FinanceTransaction.objects.all():
        # Get exchange rate for transaction date
        if not transaction.exchange_rate:
            rate, rate_date = get_exchange_rate(transaction.date)
            transaction.exchange_rate = rate
            transaction.exchange_rate_date = rate_date
        
        # Calculate amount_uzs based on currency
        if transaction.currency == 'USD':
            # USD transactions: amount_uzs = amount_usd * exchange_rate
            transaction.amount_uzs = (transaction.amount * transaction.exchange_rate).quantize(Decimal('0.01'))
        elif transaction.currency == 'UZS':
            # UZS transactions: amount_uzs = amount (original)
            transaction.amount_uzs = transaction.amount
            # Recalculate amount_usd with proper rate
            transaction.amount_usd = (transaction.amount / transaction.exchange_rate).quantize(Decimal('0.01'))
        
        transactions_to_update.append(transaction)
    
    if transactions_to_update:
        FinanceTransaction.objects.bulk_update(
            transactions_to_update,
            ['amount_uzs', 'amount_usd', 'exchange_rate', 'exchange_rate_date'],
            batch_size=100
        )
        print(f"Updated {len(transactions_to_update)} transactions with amount_uzs and exchange rates")


def reverse_populate(apps, schema_editor):
    """Reverse migration - set amount_uzs to null."""
    FinanceTransaction = apps.get_model('finance', 'FinanceTransaction')
    FinanceTransaction.objects.update(amount_uzs=None)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='amount_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Amount in UZS equivalent (auto-calculated)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate: 1 USD = X UZS (for currency conversion)', max_digits=12, null=True),
        ),
        migrations.RunPython(populate_amount_uzs, reverse_populate),
    ]
