# Generated by Django 5.1.2 on 2025-12-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='related_account',
            field=models.ForeignKey(blank=True, help_text='Related account for currency exchange transactions', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_transactions', to='finance.financeaccount'),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used for currency conversion', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('opening_balance', 'Opening Balance'), ('currency_exchange_out', 'Currency Exchange Out'), ('currency_exchange_in', 'Currency Exchange In')], max_length=30),
        ),
    ]
