# Generated by Django 5.1.2 on 2025-12-08 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_currency_exchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code, e.g. #FF5733', max_length=7)),
                ('icon', models.CharField(default='📁', help_text='Icon emoji or name', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Category owner', on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['user', 'is_active'], name='finance_exp_user_id_5f07e6_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
