# Generated by assistant on 2025-12-10
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_expensecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Make user nullable/blank
        migrations.AlterField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(help_text='Category owner (null for global categories)', on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL, null=True, blank=True),
        ),
        # Add is_global field
        migrations.AddField(
            model_name='expensecategory',
            name='is_global',
            field=models.BooleanField(default=False, db_index=True, help_text='Global categories are visible to all users'),
        ),
        # Update model options: remove unique_together and keep ordering/verbose names
        migrations.AlterModelOptions(
            name='expensecategory',
            options={
                'ordering': ('name',),
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'indexes': [
                    models.Index(fields=['user', 'is_active'], name='finance_exp_user_id_5f07e6_idx'),
                    models.Index(fields=['is_global', 'is_active'], name='finance_exp_isglobal_is_active_idx'),
                ],
            },
        ),
        # Add conditional unique constraints: global names unique, (user,name) unique for non-global
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=['name'], condition=models.Q(is_global=True), name='unique_global_category_name'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=['user', 'name'], condition=models.Q(is_global=False), name='unique_user_category_name'),
        ),
    ]
