# Generated by assistant on 2025-12-10
from django.db import migrations, transaction


DEFAULT_GLOBAL_CATEGORIES = [
    {'name': 'Maosh', 'icon': '💰', 'color': '#3B82F6'},
    {'name': 'Ijara', 'icon': '🏠', 'color': '#8B5CF6'},
    {'name': 'Kommunal xizmatlar', 'icon': '💡', 'color': '#F59E0B'},
    {'name': 'Materiallar', 'icon': '📦', 'color': '#10B981'},
    {'name': 'Transport', 'icon': '🚗', 'color': '#EF4444'},
    {'name': 'Marketing', 'icon': '📢', 'color': '#EC4899'},
    {'name': 'Uskunalar', 'icon': '🔧', 'color': '#6366F1'},
    {"name": "Ta'mirlash", 'icon': '🛠️', 'color': '#F97316'},
    {'name': 'Boshqa', 'icon': '📝', 'color': '#6B7280'},
]


def forwards(apps, schema_editor):
    ExpenseCategory = apps.get_model('finance', 'ExpenseCategory')
    with transaction.atomic():
        for entry in DEFAULT_GLOBAL_CATEGORIES:
            name = entry['name']
            if not ExpenseCategory.objects.filter(name=name, is_global=True).exists():
                ExpenseCategory.objects.create(
                    user=None,
                    is_global=True,
                    name=entry['name'],
                    icon=entry.get('icon', '📁'),
                    color=entry.get('color', '#6B7280'),
                    is_active=True,
                )


def backwards(apps, schema_editor):
    ExpenseCategory = apps.get_model('finance', 'ExpenseCategory')
    with transaction.atomic():
        ExpenseCategory.objects.filter(name__in=[e['name'] for e in DEFAULT_GLOBAL_CATEGORIES], is_global=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_global_categories_schema'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
