# Generated by Django 5.1.2 on 2025-12-10 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_seed_global_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], help_text='Type of action performed', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change was made')),
                ('old_values', models.JSONField(blank=True, help_text='Previous values before change (JSON)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values after change (JSON)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for change (optional)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
            ],
            options={
                'verbose_name': 'Finance Transaction History',
                'verbose_name_plural': 'Finance Transaction Histories',
                'ordering': ['-changed_at'],
            },
        ),
        # migrations.RenameIndex(
        #     model_name='expensecategory',
        #     new_name='finance_exp_is_glob_83d151_idx',
        #     old_name='finance_exp_isglobal_is_active_idx',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='expensecategory',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='financetransactionhistory',
            name='changed_by',
            field=models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transaction_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financetransactionhistory',
            name='transaction',
            field=models.ForeignKey(help_text='Transaction that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.financetransaction'),
        ),
        migrations.AddIndex(
            model_name='financetransactionhistory',
            index=models.Index(fields=['transaction', '-changed_at'], name='finance_fin_transac_f50655_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransactionhistory',
            index=models.Index(fields=['changed_by', '-changed_at'], name='finance_fin_changed_b7e731_idx'),
        ),
        migrations.AddIndex(
            model_name='financetransactionhistory',
            index=models.Index(fields=['action', '-changed_at'], name='finance_fin_action_3728ed_idx'),
        ),
    ]
