# Generated by Django 5.1.2 on 2025-12-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_financetransactionhistory_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='finance_exp_is_glob_83d151_idx',
            old_name='finance_exp_isglobal_is_active_idx',
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set(),
        ),
    ]
