# Generated by Django 5.1.2 on 2025-12-11 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def safe_rename_index(apps, schema_editor):
    """
    Safely rename the index only if the old name exists.
    This handles the case where migration 0012 already renamed it.
    """
    with schema_editor.connection.cursor() as cursor:
        # Check if the old index name still exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM pg_indexes
                WHERE schemaname = 'public'
                AND indexname = 'finance_exp_isglobal_is_active_idx'
            );
        """)
        old_index_exists = cursor.fetchone()[0]

        # Check if the new index already exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM pg_indexes
                WHERE schemaname = 'public'
                AND indexname = 'finance_exp_is_glob_83d151_idx'
            );
        """)
        new_index_exists = cursor.fetchone()[0]

        # Only rename if old exists and new doesn't
        if old_index_exists and not new_index_exists:
            cursor.execute("""
                ALTER INDEX finance_exp_isglobal_is_active_idx
                RENAME TO finance_exp_is_glob_83d151_idx;
            """)
        elif not old_index_exists and not new_index_exists:
            # Neither exists, create the index with the new name
            cursor.execute("""
                CREATE INDEX finance_exp_is_glob_83d151_idx
                ON finance_expensecategory (is_global, is_active);
            """)
        # If new_index_exists, do nothing - already renamed


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_rename_finance_exp_isglobal_is_active_idx_finance_exp_is_glob_83d151_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Safely handle index rename
        migrations.RunPython(safe_rename_index, migrations.RunPython.noop),

        # Add blank=True to created_by field
        migrations.AlterField(
            model_name='financetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
