# Generated by Django 5.1.2 on 2025-12-11 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_rename_finance_exp_isglobal_is_active_idx_finance_exp_is_glob_83d151_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='finance_exp_is_glob_83d151_idx',
            old_name='finance_exp_isglobal_is_active_idx',
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
