# Generated by Django 5.1.2 on 2025-12-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_safe_index_rename_and_created_by_fix'),
    ]

    operations = [
        migrations.RunSQL(
            # Check if old index exists before renaming
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'finance_exp_isglobal_is_active_idx'
                    ) THEN
                        ALTER INDEX finance_exp_isglobal_is_active_idx 
                        RENAME TO finance_exp_is_glob_83d151_idx;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'finance_exp_is_glob_83d151_idx'
                    ) THEN
                        ALTER INDEX finance_exp_is_glob_83d151_idx 
                        RENAME TO finance_exp_isglobal_is_active_idx;
                    END IF;
                END $$;
            """,
        ),
    ]
