# Generated by Django 5.1.2 on 2025-12-11 20:39

from django.db import migrations


def safe_rename_index_v2(apps, schema_editor):
    """
    Database-agnostic index rename.
    """
    from django.db import connection

    # Skip for SQLite - Django handles index renaming automatically
    if connection.vendor == 'sqlite':
        return

    with schema_editor.connection.cursor() as cursor:
        # Check if old index exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE indexname = 'finance_exp_isglobal_is_active_idx'
            );
        """)
        old_index_exists = cursor.fetchone()[0]

        if old_index_exists:
            cursor.execute("""
                ALTER INDEX finance_exp_isglobal_is_active_idx
                RENAME TO finance_exp_is_glob_83d151_idx;
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_safe_index_rename_and_created_by_fix'),
    ]

    operations = [
        migrations.RunPython(safe_rename_index_v2, migrations.RunPython.noop),
    ]
