# Generated by Django 5.1.2 on 2025-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_rename_finance_exp_isglobal_is_active_idx_finance_exp_is_glob_83d151_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('opening_balance', 'Opening Balance'), ('currency_exchange_out', 'Currency Exchange Out'), ('currency_exchange_in', 'Currency Exchange In'), ('dealer_refund', 'Dealer Refund')], max_length=30),
        ),
    ]
