# Generated by Django 5.1.2 on 2025-12-14 18:39
# Modified to handle already-renamed index

from django.db import migrations


def safe_rename_index_v3(apps, schema_editor):
    """
    Database-agnostic index rename.
    Handles case where index was already renamed in migrations 0012-0014.
    """
    from django.db import connection

    # Skip for SQLite - Django handles index renaming automatically
    if connection.vendor == 'sqlite':
        return

    with schema_editor.connection.cursor() as cursor:
        # Check if old index exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE indexname = 'finance_exp_isglobal_is_active_idx'
            );
        """)
        old_index_exists = cursor.fetchone()[0]

        if old_index_exists:
            cursor.execute("""
                ALTER INDEX finance_exp_isglobal_is_active_idx
                RENAME TO finance_exp_is_glob_83d151_idx;
            """)
        # If old index doesn't exist, it was already renamed - do nothing


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_financetransaction_type'),
    ]

    operations = [
        migrations.RunPython(safe_rename_index_v3, migrations.RunPython.noop),
    ]
