# Generated by Django 5.1.2 on 2025-12-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_financetransaction_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='finance_exp_is_glob_83d151_idx',
            old_name='finance_exp_isglobal_is_active_idx',
        ),
    ]
