# Generated by Django 5.1.2 on 2025-12-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_add_exchange_rate_performance_index'),
        ('finance', '0018_add_exchange_rate_performance_index'),
    ]

    operations = [
    ]
