# Generated by Django 5.1.2 on 2025-12-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_merge_20251218_2334'),
    ]

    operations = [
        # RenameIndex removed - index already renamed in previous migrations (0012, 0013, 0014, 0016)
        # The index 'finance_exp_isglobal_is_active_idx' was already renamed to 'finance_exp_is_glob_83d151_idx'
        migrations.AlterField(
            model_name='financetransaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
    ]
