# Generated by Django 5.1.2 on 2025-12-07 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_doormodel_collection_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_ok', models.IntegerField(default=0, help_text='Change in OK stock (positive = increase, negative = decrease)')),
                ('delta_defect', models.IntegerField(default=0, help_text='Change in defective stock (positive = increase, negative = decrease)')),
                ('previous_ok', models.IntegerField(help_text='Stock OK before adjustment')),
                ('previous_defect', models.IntegerField(help_text='Stock defect before adjustment')),
                ('new_ok', models.IntegerField(help_text='Stock OK after adjustment')),
                ('new_defect', models.IntegerField(help_text='Stock defect after adjustment')),
                ('date', models.DateField(help_text='Date of physical audit')),
                ('comment', models.TextField(blank=True, help_text='Optional notes about the adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who performed the audit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product being adjusted', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='inventory_i_created_9641aa_idx'), models.Index(fields=['date'], name='inventory_i_date_744aa2_idx'), models.Index(fields=['product', '-created_at'], name='inventory_i_product_195067_idx')],
            },
        ),
    ]
