# Generated by Django 5.2.8 on 2025-11-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
