# Generated by Django 5.2.8 on 2025-11-14 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensetype_description'),
        ('payments', '0003_paymentcard_payment_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Chiqim', 'verbose_name_plural': 'Chiqimlar'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'ordering': ['name'], 'verbose_name': 'Chiqim turi', 'verbose_name_plural': 'Chiqim turlari'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='comment',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='payments.paymentcard', verbose_name='Karta'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=10, verbose_name="To'lov usuli"),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensetype', verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='expenses_date_61c88d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expenses_status_86293f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['type', 'date'], name='expenses_type_id_cbc6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_at'], name='expenses_created_753bda_idx'),
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
        migrations.AlterModelTable(
            name='expensetype',
            table='expense_types',
        ),
    ]
