# Generated by Django 5.1.2 on 2025-11-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_amount_usd_expense_amount_uzs'),
        ('payments', '0008_cashbox_alter_cashboxopeningbalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.cashbox', verbose_name='Kassa'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='payments.paymentcard', verbose_name='Karta (eski)'),
        ),
    ]
