# Generated by Django 5.2.8 on 2025-11-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_region_manager_user'),
        ('payments', '0003_paymentcard_payment_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_uzs',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-pay_date'], name='payments_pa_pay_dat_9c7621_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['dealer'], name='payments_pa_dealer__785823_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payments_pa_method_70cfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['currency'], name='payments_pa_currenc_b1f04b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['card'], name='payments_pa_card_id_b17dfa_idx'),
        ),
    ]
