# Generated by Django 5.1.2 on 2025-11-25 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_confirmed_to_approved(apps, schema_editor):
    """Convert all existing CONFIRMED payments to APPROVED status"""
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(status='confirmed').update(
        status='approved',
        approved_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved at'),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='Receipt image'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('confirmed', 'Tasdiqlangan (eski)')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.RunPython(migrate_confirmed_to_approved, migrations.RunPython.noop),
    ]
