# Generated by Django 5.1.2 on 2025-11-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_cashboxopeningbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('cashbox_type', models.CharField(choices=[('CARD', 'Card'), ('CASH_UZS', 'Cash UZS'), ('CASH_USD', 'Cash USD')], db_column='type', max_length=20, verbose_name='Turi')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], max_length=3, verbose_name='Valyuta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
                'ordering': ['cashbox_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cashboxopeningbalance',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Kassa ochilish balansi', 'verbose_name_plural': 'Kassa ochilish balanslari'},
        ),
        migrations.RemoveIndex(
            model_name='cashboxopeningbalance',
            name='payments_ca_cashbox_idx',
        ),
        migrations.RenameIndex(
            model_name='cashboxopeningbalance',
            new_name='payments_ca_date_46c18e_idx',
            old_name='payments_ca_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cashboxopeningbalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashboxopeningbalance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Ochilish balansi'),
        ),
        migrations.AddField(
            model_name='cashboxopeningbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='cashboxopeningbalance',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Eski balans'),
        ),
        migrations.AlterField(
            model_name='cashboxopeningbalance',
            name='cashbox_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Eski kassa turi'),
        ),
        migrations.AlterField(
            model_name='cashboxopeningbalance',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Eski valyuta'),
        ),
        migrations.AlterField(
            model_name='cashboxopeningbalance',
            name='date',
            field=models.DateField(help_text='Ochilish balansi sanasi', verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbox_link', to='payments.paymentcard', verbose_name="Bog'langan karta"),
        ),
        migrations.AddField(
            model_name='cashboxopeningbalance',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='payments.cashbox', verbose_name='Kassa'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.cashbox', verbose_name='Kassa'),
        ),
        migrations.AddIndex(
            model_name='cashboxopeningbalance',
            index=models.Index(fields=['cashbox'], name='payments_ca_cashbox_1fa934_idx'),
        ),
    ]
