# Generated by Django 5.1.2 on 2025-11-27 23:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_drop_expenses_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xarajat turkumi',
                'verbose_name_plural': 'Xarajat turkumlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('bank', 'Bank hisob raqami')], max_length=20, verbose_name='Turi')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], max_length=3, verbose_name='Valyuta')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Balans')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Moliya manbai',
                'verbose_name_plural': 'Moliya manbalari',
                'ordering': ['type', 'currency', 'name'],
                'indexes': [models.Index(fields=['type', 'currency'], name='payments_fi_type_68dfe3_idx'), models.Index(fields=['is_active'], name='payments_fi_is_acti_397386_idx')],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.financesource', verbose_name='Moliya manbai'),
        ),
        migrations.CreateModel(
            name='FinanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment_in', "To'lov kirimi"), ('expense_out', 'Xarajat chiqimi'), ('adjustment', 'Tuzatish')], max_length=20, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Summa')),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Eski balans')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Yangi balans')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Havola turi')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='Havola ID')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.financesource', verbose_name='Moliya manbai')),
            ],
            options={
                'verbose_name': 'Moliya jurnali',
                'verbose_name_plural': 'Moliya jurnallari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='payments_fi_source__caf698_idx'), models.Index(fields=['reference_type', 'reference_id'], name='payments_fi_referen_c85434_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Summa')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], max_length=3, verbose_name='Valyuta')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Xarajat sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Kvitansiya rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.expensecategory', verbose_name='Turkum')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.financesource', verbose_name='Moliya manbai')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['-expense_date'], name='payments_ex_expense_8f905d_idx'), models.Index(fields=['source'], name='payments_ex_source__db6cbe_idx'), models.Index(fields=['category'], name='payments_ex_categor_c31cf2_idx'), models.Index(fields=['status'], name='payments_ex_status_e97550_idx')],
            },
        ),
    ]
