# Generated by Django 5.1.2 on 2025-11-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_expensecategory_financesource_payment_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='source',
        ),
        migrations.RemoveField(
            model_name='financelog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='financelog',
            name='source',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='source',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='FinanceLog',
        ),
        migrations.DeleteModel(
            name='FinanceSource',
        ),
    ]
