# Generated by Django 5.1.2 on 2025-11-29 22:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_remove_finance_expense_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Kod')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xarajat turi',
                'verbose_name_plural': 'Xarajat turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], max_length=3, verbose_name='Valyuta')),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Summa (asl)')),
                ('manual_rate', models.DecimalField(blank=True, decimal_places=4, help_text="USD<->UZS konvertatsiya uchun qo'lda kiritilgan kurs", max_digits=14, null=True, verbose_name="Qo'lda kurs")),
                ('amount_uzs', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Summa UZS')),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='Summa USD')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.cashbox', verbose_name='Kassa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.expensecategory', verbose_name='Xarajat turi')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['-expense_date'], name='payments_ex_expense_8f905d_idx'), models.Index(fields=['status'], name='payments_ex_status_e97550_idx'), models.Index(fields=['category'], name='payments_ex_categor_c31cf2_idx'), models.Index(fields=['cashbox'], name='payments_ex_cashbox_f35c4d_idx'), models.Index(fields=['currency'], name='payments_ex_currenc_3d70d4_idx')],
            },
        ),
    ]
