# Generated by Django 5.1.2 on 2025-12-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_add_expense_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='cashbox_type',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH_UZS', 'Cash UZS'), ('CASH_USD', 'Cash USD'), ('BANK', 'Bank')], db_column='type', max_length=20, verbose_name='Turi'),
        ),
    ]
