# Generated by Django 5.1.2 on 2025-12-10 17:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_add_opening_balance_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ('name',), 'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',), 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Physical address of the dealer', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='code',
            field=models.CharField(help_text='Unique identifier code for the dealer', max_length=32, unique=True, verbose_name='Dealer code'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='contact',
            field=models.CharField(blank=True, help_text='Name of contact person at dealer', max_length=255, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when dealer was created', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='debt_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy field: Dealer debt in USD (deprecated, use balance service)', max_digits=14, verbose_name='Debt (USD) - Deprecated'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this dealer is currently active', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='manager_user',
            field=models.ForeignKey(blank=True, help_text='Sales manager assigned to this dealer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_dealers', to=settings.AUTH_USER_MODEL, verbose_name='Sales manager'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(help_text='Full name of the dealer/customer', max_length=255, verbose_name='Dealer name'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opening balance amount in opening_balance_currency', max_digits=18, verbose_name='Opening balance'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='opening_balance_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', help_text='Currency of opening balance (USD or UZS)', max_length=3, verbose_name='Opening balance currency'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='opening_balance_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date when opening balance was set', verbose_name='Opening balance date'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='opening_balance_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field: Opening balance in USD', max_digits=14, verbose_name='Opening balance (USD) - Legacy'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='opening_balance_uzs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field: Opening balance in UZS', max_digits=18, verbose_name='Opening balance (UZS) - Legacy'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number', max_length=50, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='region',
            field=models.ForeignKey(help_text='Geographic region where dealer is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='dealers.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='region',
            name='manager_user',
            field=models.ForeignKey(blank=True, help_text='Sales manager assigned to this region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_regions', to=settings.AUTH_USER_MODEL, verbose_name='Region manager'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Unique name of the region', max_length=120, unique=True, verbose_name='Region name'),
        ),
    ]
