# Generated by Django 5.1.2 on 2025-12-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_alter_dealer_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='include_in_manager_kpi',
            field=models.BooleanField(default=True, help_text="Whether this dealer's sales and payments should be included in manager KPI calculation", verbose_name='Include in manager KPI'),
        ),
    ]
