# Generated by Django 5.1.2 on 2025-12-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_add_debt_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dealer',
            name='opening_balance_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dealer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
