# Generated by Django 5.1.2 on 2025-12-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_add_include_in_manager_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='portal_enabled',
            field=models.BooleanField(default=False, help_text='Whether this dealer can access the dealer portal', verbose_name='Portal access enabled'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='portal_password',
            field=models.CharField(blank=True, help_text='Hashed password for dealer portal access', max_length=128, null=True, verbose_name='Portal password (hashed)'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='portal_username',
            field=models.CharField(blank=True, help_text='Auto-generated username for dealer portal access', max_length=100, null=True, unique=True, verbose_name='Portal username'),
        ),
    ]
