# Generated by Django 5.1.2 on 2025-11-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_records', to='dealers.dealer')),
            ],
            options={
                'ordering': ('-recorded_at',),
                'unique_together': {('dealer', 'name', 'recorded_at')},
            },
        ),
    ]
