# Generated by Django 5.2.8 on 2025-11-14 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=10, verbose_name='Turi')),
                ('source', models.CharField(choices=[('payment', "To'lov"), ('expense', 'Chiqim'), ('adjustment', 'Tuzatish'), ('return', 'Qaytarish')], max_length=20, verbose_name='Manba')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS')], default='USD', max_length=3, verbose_name='Valyuta')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Tavsif')),
                ('ref_model', models.CharField(blank=True, max_length=50, verbose_name='Model')),
                ('ref_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_records', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Kassa operatsiyasi',
                'verbose_name_plural': 'Kassa operatsiyalari',
                'db_table': 'ledger_records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='ledger_reco_date_6d1609_idx'), models.Index(fields=['type', 'date'], name='ledger_reco_type_e394e7_idx'), models.Index(fields=['source'], name='ledger_reco_source_63ddfa_idx'), models.Index(fields=['ref_model', 'ref_id'], name='ledger_reco_ref_mod_954b23_idx')],
            },
        ),
    ]
