# Generated by Django 5.2.8 on 2025-11-12 20:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_paymentcard_payment_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card')], max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_account', to='payments.paymentcard')),
            ],
            options={
                'ordering': ('type', 'name'),
                'unique_together': {('type', 'payment_card')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment_in', 'Payment In'), ('expense_out', 'Expense Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('ref_app', models.CharField(blank=True, max_length=32)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgeraccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='ledger_ledg_date_f3a643_idx'), models.Index(fields=['ref_app', 'ref_id'], name='ledger_ledg_ref_app_118875_idx'), models.Index(fields=['account', 'date'], name='ledger_ledg_account_f78e6b_idx')],
            },
        ),
    ]
