# Generated by Django 5.2.8 on 2025-11-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_reconciled', to=settings.AUTH_USER_MODEL),
        ),
    ]
