# Generated by Django 5.2.8 on 2025-11-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerrecord',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Summa USD'),
        ),
        migrations.AddField(
            model_name='ledgerrecord',
            name='amount_uzs',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Summa UZS'),
        ),
    ]
