# Generated by Django 5.1.2 on 2025-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_2fa_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
