# Generated by Django 5.1.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dashboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last activity timestamp', null=True),
        ),
    ]
