# Generated by Django 5.1.2 on 2025-12-19 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When user was archived', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_reason',
            field=models.CharField(blank=True, choices=[('terminated', "Ishdan bo'shatilgan"), ('replaced', 'Almashtirilgan'), ('resigned', "O'zi ketgan"), ('other', 'Boshqa sabab')], help_text='Reason for archiving', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replaced_at', models.DateTimeField(auto_now_add=True, help_text='When replacement occurred')),
                ('comment', models.TextField(blank=True, help_text='Reason or notes for replacement')),
                ('new_user', models.ForeignKey(help_text='Replacement user', on_delete=django.db.models.deletion.CASCADE, related_name='replaced_to', to=settings.AUTH_USER_MODEL)),
                ('old_user', models.ForeignKey(help_text='User being replaced', on_delete=django.db.models.deletion.CASCADE, related_name='replaced_from', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(help_text='Admin who performed the replacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Replacement',
                'verbose_name_plural': 'User Replacements',
                'db_table': 'users_replacement',
                'ordering': ['-replaced_at'],
            },
        ),
    ]
