# Generated by Django 5.1.2 on 2025-12-19 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_archived_at_user_archived_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreplacement',
            name='replacement_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Effective date of replacement'),
        ),
    ]
