# Generated by Django 5.2.8 on 2025-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('director', 'Director'), ('accountant', 'Accountant'), ('warehouse', 'Warehouse'), ('sales', 'Sales Manager')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
